### ISSUE TITLE
C stack usage is too close to the limit

### ISSUE THREAD

**Issue by meumesmo** [braverock/FinancialInstrument#2]
Hello, I'm getting the following error when trying to run the command:
`stock(data, currency = "USD")
`
Error: C stack usage  15923264 is too close to the limit

Thanks

**Comment by braverock** [comment]
It looks like `data` is a data object, not a string identifier for the stock.

Normally, this would look something like:

`stock('AMZN', currency='USD')`

If you are still having trouble, please include `sessionInfo()` and a fully reproducible example.

**Comment by meumesmo** [comment]
Thanks!
